### PR TITLE
Correct adding slash to control->tmpdir. off-by-one error.

### PR DESCRIPTION
**Pull request by pete4abw**
off by one error. sorry...

### CODE REVIEW

**Comment by ckolivas** [comment]
:(

**Comment by pete4abw** [comment]
Not a fatal error. Just will create two slashes if the tmpdir had a trailing slash. If tmpdir had no trailing slash, no problem.

**Comment by ckolivas** [comment]
Phew, I just released a version. Two slashes are harmless.

**Comment by pete4abw** [comment]
It was late. Here's debug output.

1283            if (control->tmpdir[len] != '/')
2: control->tmpdir = 0x659060 "/tmp/dir/"
1: eptr = 0x7fffffffee0b "/tmp/dir/"
(gdb) n
1284                    control->tmpdir[len] = '/'; /* need a trailing
slash */
2: control->tmpdir = 0x659060 "/tmp/dir/"
1: eptr = 0x7fffffffee0b "/tmp/dir/"
(gdb) n
1285            control->tmpdir[len+1] = '\0';
2: control->tmpdir = 0x659060 "/tmp/dir//"
1: eptr = 0x7fffffffee0b "/tmp/dir/"
(gdb) n
1287            return true;
2: control->tmpdir = 0x659060 "/tmp/dir//"
1: eptr = 0x7fffffffee0b "/tmp/dir/"
(gdb) n
1288    }
2: control->tmpdir = 0x659060 "/tmp/dir//"
1: eptr = 0x7fffffffee0b "/tmp/dir/"

**Pull request merged**
