### PR TITLE
switch to chunk-wide read/write loops when loading and dumping in stdio mode

### PR DESCRIPTION
**Pull request by tpwrules**
This fixes the high CPU usage and slow speeds observed when using stdio mode and temporary files need to be spilled to disk.

Using a 56GiB output archive decompressed to /dev/null on a SATA SSD, real decompression time is decreased by 81%  (1968 seconds to 407 seconds) and CPU time is decreased by 60% (2662 seconds to 1070 seconds).

### CODE REVIEW

**Comment by pete4abw** [comment]
I'm curious if this has been tested to output to a real file and the file with `lrzip` passed a `-t` or `-dc` check?

**Comment by tpwrules** [comment]
I did check that the files I decompressed had hashes that matched the originals, but I'm not sure how the built in test modes apply given that lrzip theoretically has no access to the output file. In my case I pipe it directly into another command.

Are you seeing corruption? I have seen problems with older lrzips, in particular 0.631, that cause it to crash when extracting archives and there is a reduced amount of memory available. But I upgraded lrzip and they extract fine now. Maybe there are still other bugs?

**Comment by pete4abw** [comment]
I have not implemented these changes in my version of lrzip. I may throw it into the whats-next branch and see. Your code would also impact commands such as `tar -I lrizip .....`. I'm not a piping expert which is why I am hesitant.

**Comment by okutoo** [comment]
@[_****_]()image

**Review by okutoo — COMMENTED** [review]
orG() i ‰‰####====<>|||||||||||...

**Pull request merged**
